force-app/main/default/objects/Deal_Building__c/Deal_Building__c.object-meta.xml
<CustomObject>
    <label>Deal Unit</label>
    <nameField>
        <displayFormat>DU# {00000000}</displayFormat>
        <label>Deal Unit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_Building__c/fields/Asking_Price__c.field-meta.xml
<CustomField>
    <fullName>Asking_Price__c</fullName>
    <formula>Building__r.Asking_Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Asking Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Deal_Building__c/fields/LandArea__c.field-meta.xml
<CustomField>
    <fullName>LandArea__c</fullName>
    <formula>Building__r.LandArea__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Land Area</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Deal_Building__c/fields/LandSellableAmount__c.field-meta.xml
<CustomField>
    <fullName>LandSellableAmount__c</fullName>
    <formula>Building__r.LandSellableAmount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Land Sellable Amount</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Deal_Building__c/fields/LandSellableAreaSqm__c.field-meta.xml
<CustomField>
    <fullName>LandSellableAreaSqm__c</fullName>
    <formula>Building__r.LandSellableAreaSqm__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Land Sellable Area Sqm</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Deal_Building__c/fields/Lobby_Area_Sqm__c.field-meta.xml
<CustomField>
    <fullName>Lobby_Area_Sqm__c</fullName>
    <formula>Building__r.Lobby_Area_Sqm__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lobby Area Sqm</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Deal_Building__c/fields/Minimum_Annual_Rent__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Annual_Rent__c</fullName>
    <formula>Building__r.Minimum_Annual_Rent__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Minimum Annual Rent</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Deal_Building__c/fields/PreLaunchPrice__c.field-meta.xml
<CustomField>
    <fullName>PreLaunchPrice__c</fullName>
    <formula>Building__r.PreLaunchPrice__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Pre Launch Price</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Deal_Building__c/fields/Price_Sqm_SAR_Lobby__c.field-meta.xml
<CustomField>
    <fullName>Price_Sqm_SAR_Lobby__c</fullName>
    <formula>Building__r.Price_Sqm_SAR_Lobby__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Price Sqm SAR / Lobby</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Deal_Building__c/fields/Service_Area_Sqm__c.field-meta.xml
<CustomField>
    <fullName>Service_Area_Sqm__c</fullName>
    <formula>Building__r.Service_Area_Sqm__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Service Area Sqm</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Deal_Building__c/fields/Terrace_Area_Sqm__c.field-meta.xml
<CustomField>
    <fullName>Terrace_Area_Sqm__c</fullName>
    <formula>Building__r.Terrace_Area_Sqm__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Terrace Area Sqm</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Deal_Building__c/fields/Total_Leasable_Area_Sqm__c.field-meta.xml
<CustomField>
    <fullName>Total_Leasable_Area_Sqm__c</fullName>
    <formula>Building__r.Total_Leasable_Area_Sqm__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Leasable Area Sqm</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Deal_Building__c/fields/Total_NSA__c.field-meta.xml
<CustomField>
    <fullName>Total_NSA__c</fullName>
    <formula>Building__r.Total_NSA__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total (NSA)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Deal_Building__c/fields/Total_Prices_Lobby__c.field-meta.xml
<CustomField>
    <fullName>Total_Prices_Lobby__c</fullName>
    <formula>Building__r.Total_Prices_Lobby_Areas__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Prices (Lobby)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Deal_Building__c/fields/Total_Prices_Services_Areas__c.field-meta.xml
<CustomField>
    <fullName>Total_Prices_Services_Areas__c</fullName>
    <formula>Building__r.Total_Prices_Services_Areas__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Prices (Services Areas)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Deal_Building__c/fields/Total_Prices_Terraces_Areas__c.field-meta.xml
<CustomField>
    <fullName>Total_Prices_Terraces_Areas__c</fullName>
    <formula>Building__r.Total_Prices_Terraces_Areas__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Prices (Terraces Areas)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Deal_Building__c/fields/Total_Selling_Price_SAR__c.field-meta.xml
<CustomField>
    <fullName>Total_Selling_Price_SAR__c</fullName>
    <label>Total Selling Price SAR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Deal_Building__c/fields/Unit_Area_Sqm__c.field-meta.xml
<CustomField>
    <fullName>Unit_Area_Sqm__c</fullName>
    <formula>Building__r.Unit_Area_Sqm__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unit Area / Sqm</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Deal_Building__c/fields/Unit_Area_Sqm_NSA__c.field-meta.xml
<CustomField>
    <fullName>Unit_Area_Sqm_NSA__c</fullName>
    <formula>Building__r.Unit_Area_Sqm_NSA__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unit Area Sqm (NSA)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Deal_Building__c/fields/Unit_No__c.field-meta.xml
<CustomField>
    <fullName>Unit_No__c</fullName>
    <formula>Building__r.Unit_No__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unit No</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal_Building__c/fields/VillaArea__c.field-meta.xml
<CustomField>
    <fullName>VillaArea__c</fullName>
    <formula>Building__r.VillaArea__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Villa Area</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Deal_Building__c/fields/VillaSellableAreaSqm__c.field-meta.xml
<CustomField>
    <fullName>VillaSellableAreaSqm__c</fullName>
    <formula>Building__r.VillaSellableAreaSqm__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Villa Sellable Area Sqm</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Area_Sqm__c.field-meta.xml
<CustomField>
    <fullName>Area_Sqm__c</fullName>
    <label>Gross Area Sqm</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/BuildUpArea__c.field-meta.xml
<CustomField>
    <fullName>BuildUpArea__c</fullName>
    <label>Build Up Area</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/LandArea__c.field-meta.xml
<CustomField>
    <fullName>LandArea__c</fullName>
    <label>Land Area</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/LandPricePerSqm__c.field-meta.xml
<CustomField>
    <fullName>LandPricePerSqm__c</fullName>
    <label>Land Price Per Sqm</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/LandSellableAmount__c.field-meta.xml
<CustomField>
    <fullName>LandSellableAmount__c</fullName>
    <label>Land Sellable Amount</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lobby_Area_Sqm__c.field-meta.xml
<CustomField>
    <fullName>Lobby_Area_Sqm__c</fullName>
    <label>Lobby Area Sqm</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Minimum_Acceptable_Rent__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Acceptable_Rent__c</fullName>
    <label>Minimum Acceptable Rent (SAR/Year)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PreLaunchPrice__c.field-meta.xml
<CustomField>
    <fullName>PreLaunchPrice__c</fullName>
    <label>Minimum Price</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Price_Sqm_SAR_Lobby__c.field-meta.xml
<CustomField>
    <fullName>Price_Sqm_SAR_Lobby__c</fullName>
    <label>Lobby Rate per Sqm</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Price_Sqm_SAR_Service__c.field-meta.xml
<CustomField>
    <fullName>Price_Sqm_SAR_Service__c</fullName>
    <label>Service Area Rate per Sqm</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Price_Sqm_SAR_Terrace__c.field-meta.xml
<CustomField>
    <fullName>Price_Sqm_SAR_Terrace__c</fullName>
    <label>Terrace Rate per Sqm</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Price_Sqm_SAR_Unit__c.field-meta.xml
<CustomField>
    <fullName>Price_Sqm_SAR_Unit__c</fullName>
    <label>Unit Rate per Sqm</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Rate_per_Sqm_SR_Sqm__c.field-meta.xml
<CustomField>
    <fullName>Rate_per_Sqm_SR_Sqm__c</fullName>
    <label>Rate per Sqm (SR/Sqm)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Service_Area_Sqm__c.field-meta.xml
<CustomField>
    <fullName>Service_Area_Sqm__c</fullName>
    <label>Service Area Sqm</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Terrace_Area_Sqm__c.field-meta.xml
<CustomField>
    <fullName>Terrace_Area_Sqm__c</fullName>
    <label>Terrace Area Sqm</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Total_Annual_Rent__c.field-meta.xml
<CustomField>
    <fullName>Total_Annual_Rent__c</fullName>
    <label>Total Annual Rent</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Total_Annual_Rent_SR_Annum__c.field-meta.xml
<CustomField>
    <fullName>Total_Annual_Rent_SR_Annum__c</fullName>
    <label>Total Annual Rent SR/Annum</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TotalSellingPrice__c.field-meta.xml
<CustomField>
    <fullName>TotalSellingPrice__c</fullName>
    <label>Total Selling Price</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Unit_Area_Sqm__c.field-meta.xml
<CustomField>
    <fullName>Unit_Area_Sqm__c</fullName>
    <label>Unit Area Sqm</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Unit_Number__c.field-meta.xml
<CustomField>
    <fullName>Unit_Number__c</fullName>
    <label>Unit Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Unit_Size_Sqm__c.field-meta.xml
<CustomField>
    <fullName>Unit_Size_Sqm__c</fullName>
    <label>Unit Size (Sqm)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Offices.recordType-meta.xml
<RecordType>
    <fullName>Offices</fullName>
    <active>true</active>
    <businessProcess>Offices</businessProcess>
    <label>Offices</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Residential.recordType-meta.xml
<RecordType>
    <fullName>Residential</fullName>
    <active>true</active>
    <businessProcess>Offices</businessProcess>
    <label>Residential</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Retail.recordType-meta.xml
<RecordType>
    <fullName>Retail</fullName>
    <active>true</active>
    <businessProcess>Retail</businessProcess>
    <label>Retail</label>
</RecordType>

force-app/main/default/classes/DealBuildingAggregatorTest.cls
@IsTest
private class DealBuildingAggregatorTest {
    private static Deal_Building__c dbWithValues(Map<String, Object> values) {
        return (Deal_Building__c) JSON.deserialize(
            JSON.serialize(values),
            Deal_Building__c.class
        );
    }

    @IsTest
    static void applyToOpportunity_shouldAggregateOfficeFields() {
        DealBuildingAggregator aggregator = new DealBuildingAggregator('Offices');

        Deal_Building__c db = dbWithValues(new Map<String, Object>{
            'Total_Selling_Price_SAR__c' => 1000,
            'Service_Area_Sqm__c' => 10,
            'Terrace_Area_Sqm__c' => 5,
            'Total_Prices_Services_Areas__c' => 200,
            'Total_Prices_Terraces_Areas__c' => 100,
            'Unit_Area_Sqm_NSA__c' => 20,
            'Total_NSA__c' => 400,
            'Lobby_Area_Sqm__c' => 2,
            'Total_Prices_Lobby__c' => 40,
            'Total_Leasable_Area_Sqm__c' => 50
        });

        aggregator.add(db);

        Opportunity opp = new Opportunity();
        aggregator.applyToOpportunity(opp);

        System.assertEquals(1000, opp.Amount);
        System.assertEquals(20, opp.Unit_Size_SQM__c);
        System.assertEquals(400, opp.Minimum_Acceptable_Rent__c);
        System.assertEquals(50, opp.Area_Sqm__c);
        System.assertEquals(1000, opp.Total_Annual_Rent_SR_Annum__c);
        System.assertEquals(20, opp.Price_Sqm_SAR_Unit__c);
        System.assertEquals(20, opp.Price_Sqm_SAR_Service__c);
        System.assertEquals(20, opp.Price_Sqm_SAR_Terrace__c);
        System.assertEquals(20, opp.Price_Sqm_SAR_Lobby__c);
        System.assertEquals(20, opp.Rate_per_Sqm_SR_Sqm__c);
    }

    @IsTest
    static void applyToOpportunity_shouldAggregateRetailFields() {
        DealBuildingAggregator aggregator = new DealBuildingAggregator('Retail');

        aggregator.add(dbWithValues(new Map<String, Object>{
            'Total_Selling_Price_SAR__c' => 500,
            'Unit_Area_Sqm__c' => 10,
            'Asking_Price__c' => 500,
            'Minimum_Annual_Rent__c' => 50,
            'Unit_No__c' => 'A1'
        }));
        aggregator.add(dbWithValues(new Map<String, Object>{
            'Total_Selling_Price_SAR__c' => 300,
            'Unit_Area_Sqm__c' => 10,
            'Asking_Price__c' => 300,
            'Minimum_Annual_Rent__c' => 30,
            'Unit_No__c' => 'B2'
        }));

        Opportunity opp = new Opportunity();
        aggregator.applyToOpportunity(opp);

        System.assertEquals(800, opp.Amount);
        System.assertEquals(20, opp.Unit_Size_SQM__c);
        System.assertEquals(20, opp.Area_Sqm__c);
        System.assertEquals(800, opp.Total_Annual_Rent__c);
        System.assertEquals(40, opp.Rate_per_Sqm_SR_Sqm__c);
        System.assertEquals('A1,B2', opp.Unit_Number__c);
        System.assertEquals(80, opp.Minimum_Acceptable_Rent__c);
    }

    @IsTest
    static void applyToOpportunity_shouldAggregateResidentialPropertyFields() {
        DealBuildingAggregator aggregator = new DealBuildingAggregator('Residential Property');

        aggregator.add(dbWithValues(new Map<String, Object>{
            'LandArea__c' => 100,
            'LandSellableAreaSqm__c' => 30,
            'LandSellableAmount__c' => 3000,
            'VillaArea__c' => 50,
            'VillaSellableAreaSqm__c' => 40,
            'PreLaunchPrice__c' => 700,
            'Asking_Price__c' => 5000,
            'Total_Selling_Price_SAR__c' => 5500
        }));

        Opportunity opp = new Opportunity();
        aggregator.applyToOpportunity(opp);

        System.assertEquals(100, opp.LandArea__c);
        System.assertEquals(30, opp.LandPricePerSqm__c);
        System.assertEquals(3000, opp.LandSellableAmount__c);
        System.assertEquals(50, opp.BuildUpArea__c);
        System.assertEquals(700, opp.PreLaunchPrice__c);
       // System.assertEquals(5000, opp.Amount);
       // System.assertEquals(5000, opp.TotalSellingPrice__c);
    }
}