force-app/main/default/objects/Deal_Building__c/Deal_Building__c.object-meta.xml
<CustomObject>
    <label>Deal Unit</label>
    <nameField>
        <displayFormat>DU# {00000000}</displayFormat>
        <label>Deal Unit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_Building__c/fields/Asking_Price__c.field-meta.xml
<CustomField>
    <fullName>Asking_Price__c</fullName>
    <formula>Building__r.Asking_Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Asking Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Deal_Building__c/fields/LandArea__c.field-meta.xml
<CustomField>
    <fullName>LandArea__c</fullName>
    <formula>Building__r.LandArea__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Land Area</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Deal_Building__c/fields/LandSellableAmount__c.field-meta.xml
<CustomField>
    <fullName>LandSellableAmount__c</fullName>
    <formula>Building__r.LandSellableAmount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Land Sellable Amount</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Deal_Building__c/fields/Leasing_Rate_Sqm_SAR__c.field-meta.xml
<CustomField>
    <fullName>Leasing_Rate_Sqm_SAR__c</fullName>
    <formula>Building__r.Leasing_Rate_Sqm_SAR__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Leasing Rate / Sqm SAR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Deal_Building__c/fields/Lobby_Area_Sqm__c.field-meta.xml
<CustomField>
    <fullName>Lobby_Area_Sqm__c</fullName>
    <formula>Building__r.Lobby_Area_Sqm__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lobby Area Sqm</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Deal_Building__c/fields/Minimum_Annual_Rent__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Annual_Rent__c</fullName>
    <formula>Building__r.Minimum_Annual_Rent__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Minimum Annual Rent</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Deal_Building__c/fields/PreLaunchPrice__c.field-meta.xml
<CustomField>
    <fullName>PreLaunchPrice__c</fullName>
    <formula>Building__r.PreLaunchPrice__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Pre Launch Price</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Deal_Building__c/fields/Price_Sqm_SAR_Lobby__c.field-meta.xml
<CustomField>
    <fullName>Price_Sqm_SAR_Lobby__c</fullName>
    <formula>Building__r.Price_Sqm_SAR_Lobby__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Price Sqm SAR / Lobby</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Deal_Building__c/fields/Service_Area_Sqm__c.field-meta.xml
<CustomField>
    <fullName>Service_Area_Sqm__c</fullName>
    <formula>Building__r.Service_Area_Sqm__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Service Area Sqm</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Deal_Building__c/fields/Terrace_Area_Sqm__c.field-meta.xml
<CustomField>
    <fullName>Terrace_Area_Sqm__c</fullName>
    <formula>Building__r.Terrace_Area_Sqm__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Terrace Area Sqm</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Deal_Building__c/fields/Total_Leasable_Area_Sqm__c.field-meta.xml
<CustomField>
    <fullName>Total_Leasable_Area_Sqm__c</fullName>
    <formula>Building__r.Total_Leasable_Area_Sqm__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Leasable Area Sqm</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Deal_Building__c/fields/Total_NSA__c.field-meta.xml
<CustomField>
    <fullName>Total_NSA__c</fullName>
    <formula>Building__r.Total_NSA__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total (NSA)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Deal_Building__c/fields/Total_Prices_Lobby__c.field-meta.xml
<CustomField>
    <fullName>Total_Prices_Lobby__c</fullName>
    <formula>Building__r.Total_Prices_Lobby_Areas__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Prices (Lobby)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Deal_Building__c/fields/Total_Prices_Services_Areas__c.field-meta.xml
<CustomField>
    <fullName>Total_Prices_Services_Areas__c</fullName>
    <formula>Building__r.Total_Prices_Services_Areas__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Prices (Services Areas)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Deal_Building__c/fields/Total_Prices_Terraces_Areas__c.field-meta.xml
<CustomField>
    <fullName>Total_Prices_Terraces_Areas__c</fullName>
    <formula>Building__r.Total_Prices_Terraces_Areas__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Prices (Terraces Areas)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Deal_Building__c/fields/Total_Selling_Price_SAR__c.field-meta.xml
<CustomField>
    <fullName>Total_Selling_Price_SAR__c</fullName>
    <label>Total Selling Price SAR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Deal_Building__c/fields/Unit_Area_Sqm__c.field-meta.xml
<CustomField>
    <fullName>Unit_Area_Sqm__c</fullName>
    <formula>Building__r.Unit_Area_Sqm__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unit Area / Sqm</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Deal_Building__c/fields/Unit_Area_Sqm_NSA__c.field-meta.xml
<CustomField>
    <fullName>Unit_Area_Sqm_NSA__c</fullName>
    <formula>Building__r.Unit_Area_Sqm_NSA__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unit Area Sqm (NSA)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Deal_Building__c/fields/Unit_No__c.field-meta.xml
<CustomField>
    <fullName>Unit_No__c</fullName>
    <formula>Building__r.Unit_No__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unit No</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deal_Building__c/fields/VillaArea__c.field-meta.xml
<CustomField>
    <fullName>VillaArea__c</fullName>
    <formula>Building__r.VillaArea__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Villa Area</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Deal_Building__c/fields/VillaSellableAreaSqm__c.field-meta.xml
<CustomField>
    <fullName>VillaSellableAreaSqm__c</fullName>
    <formula>Building__r.VillaSellableAreaSqm__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Villa Sellable Area Sqm</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Area_Sqm__c.field-meta.xml
<CustomField>
    <fullName>Area_Sqm__c</fullName>
    <label>Gross Area Sqm</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Asking_Rate_Sqm__c.field-meta.xml
<CustomField>
    <fullName>Asking_Rate_Sqm__c</fullName>
    <label>Asking Rate/Sqm</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/LandArea__c.field-meta.xml
<CustomField>
    <fullName>LandArea__c</fullName>
    <label>Land Area</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/LandSellableAmount__c.field-meta.xml
<CustomField>
    <fullName>LandSellableAmount__c</fullName>
    <label>Land Sellable Amount</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lobby_Area_Sqm__c.field-meta.xml
<CustomField>
    <fullName>Lobby_Area_Sqm__c</fullName>
    <label>Lobby Area Sqm</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Minimum_Acceptable_Rate_Sqm_SR_Sqm__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Acceptable_Rate_Sqm_SR_Sqm__c</fullName>
    <label>Minimum Acceptable Rate/Sqm (SAR/Sqm)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Minimum_Acceptable_Rent__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Acceptable_Rent__c</fullName>
    <label>Minimum Acceptable Rent (SAR/Year)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PreLaunchPrice__c.field-meta.xml
<CustomField>
    <fullName>PreLaunchPrice__c</fullName>
    <label>Minimum Price</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Price_Sqm_SAR_Lobby__c.field-meta.xml
<CustomField>
    <fullName>Price_Sqm_SAR_Lobby__c</fullName>
    <label>Lobby Rate per Sqm</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Price_Sqm_SAR_Service__c.field-meta.xml
<CustomField>
    <fullName>Price_Sqm_SAR_Service__c</fullName>
    <label>Service Area Rate per Sqm</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Price_Sqm_SAR_Terrace__c.field-meta.xml
<CustomField>
    <fullName>Price_Sqm_SAR_Terrace__c</fullName>
    <label>Terrace Rate per Sqm</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Price_Sqm_SAR_Unit__c.field-meta.xml
<CustomField>
    <fullName>Price_Sqm_SAR_Unit__c</fullName>
    <label>Unit Rate per Sqm</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Rate_per_Sqm_SR_Sqm__c.field-meta.xml
<CustomField>
    <fullName>Rate_per_Sqm_SR_Sqm__c</fullName>
    <label>Rate per Sqm (SR/Sqm)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Service_Area_SAR__c.field-meta.xml
<CustomField>
    <fullName>Service_Area_SAR__c</fullName>
    <label>Service Area SAR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Service_Area_Sqm__c.field-meta.xml
<CustomField>
    <fullName>Service_Area_Sqm__c</fullName>
    <label>Service Area Sqm</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Terrace_Area_SAR__c.field-meta.xml
<CustomField>
    <fullName>Terrace_Area_SAR__c</fullName>
    <label>Terrace Area SAR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Terrace_Area_Sqm__c.field-meta.xml
<CustomField>
    <fullName>Terrace_Area_Sqm__c</fullName>
    <label>Terrace Area Sqm</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Total_Annual_Rent__c.field-meta.xml
<CustomField>
    <fullName>Total_Annual_Rent__c</fullName>
    <label>Total Annual Rent</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Total_Annual_Rent_SR_Annum__c.field-meta.xml
<CustomField>
    <fullName>Total_Annual_Rent_SR_Annum__c</fullName>
    <label>Total Annual Rent SR/Annum</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Total_Asking_Rent_SR__c.field-meta.xml
<CustomField>
    <fullName>Total_Asking_Rent_SR__c</fullName>
    <label>Total Asking Rent (SR)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Total_Prices_Lobby_Areas__c.field-meta.xml
<CustomField>
    <fullName>Total_Prices_Lobby_Areas__c</fullName>
    <label>Total Prices (Lobby Areas)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Total_Prices_Service_Area__c.field-meta.xml
<CustomField>
    <fullName>Total_Prices_Service_Area__c</fullName>
    <label>Total Prices (Service Area)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Total_Prices_Terrace_Area__c.field-meta.xml
<CustomField>
    <fullName>Total_Prices_Terrace_Area__c</fullName>
    <label>Total Prices (Terrace Area)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Total_Prices_Unit_Area__c.field-meta.xml
<CustomField>
    <fullName>Total_Prices_Unit_Area__c</fullName>
    <label>Total Prices (Unit Area)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Unit_Area_Sqm__c.field-meta.xml
<CustomField>
    <fullName>Unit_Area_Sqm__c</fullName>
    <label>Unit Area Sqm</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Unit_Size_Sqm__c.field-meta.xml
<CustomField>
    <fullName>Unit_Size_Sqm__c</fullName>
    <label>Unit Size (Sqm)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Offices.recordType-meta.xml
<RecordType>
    <fullName>Offices</fullName>
    <active>true</active>
    <businessProcess>Offices</businessProcess>
    <label>Offices</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Residential.recordType-meta.xml
<RecordType>
    <fullName>Residential</fullName>
    <active>true</active>
    <businessProcess>Offices</businessProcess>
    <label>Residential</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Retail.recordType-meta.xml
<RecordType>
    <fullName>Retail</fullName>
    <active>true</active>
    <businessProcess>Retail</businessProcess>
    <label>Retail</label>
</RecordType>

force-app/main/default/classes/DealBuildingAggregator.cls
public class DealBuildingAggregator {
    
    private String recordTypeName;
    
    // Accumulated values
    private Decimal totalAmount = 0;
    private Decimal totalUnitSize = 0;
    private Decimal totalServiceAreaSqm = 0;
    private Decimal totalTerraceAreaSqm = 0;
    private Decimal totalServiceAreaSAR = 0;
    private Decimal totalTerraceAreaSAR = 0;
    private Decimal totalMinimumAcceptableRent = 0;
    
    // Office-specific fields
    private Decimal totalUnitAreaSqmNSA = 0;
    private Decimal totalNSA = 0;
    private Decimal totalPricesServicesAreas = 0;
    private Decimal totalPricesTerraceAreas = 0;
    private Decimal totalLobbyAreaSqm = 0;
    private Decimal totalPricesLobby = 0;
    private Decimal totalLeasingRate = 0;
    private Decimal totalLeasableAreaSqm = 0;
    private Decimal totalSellingPriceForRate = 0;
    
    // Retail-specific fields
    private List<String> unitNumbers = new List<String>();
    private Decimal totalUnitAreaSqm = 0;
    private Decimal totalAskingPrice = 0;
    private Decimal totalAnnualRent = 0;

    //Residential property-specific fields
    private Decimal totalLandArea = 0;
    private Decimal totalLandSellableAmount = 0;
    private Decimal totalVillaArea = 0;
    private Decimal totalVillaSellableAreaSqm = 0;
    private Decimal totalPreLaunchPrice = 0;
    private Decimal totalSellingPrice = 0;
    
    public DealBuildingAggregator(String recordTypeName) {
        this.recordTypeName = recordTypeName;
    }
    
    /**
     * Adds a Deal_Building record to the aggregation
     */
    public void add(Deal_Building__c db) {
        // Common fields
        totalAmount += nvl(db.Total_Selling_Price_SAR__c);
        totalServiceAreaSqm += nvl(db.Service_Area_Sqm__c);
        totalTerraceAreaSqm += nvl(db.Terrace_Area_Sqm__c);
        totalServiceAreaSAR += nvl(db.Total_Prices_Services_Areas__c);
        totalTerraceAreaSAR += nvl(db.Total_Prices_Terraces_Areas__c);
        
        //switch case for record type
        switch on recordTypeName {
            when 'Offices' {
                addOfficeFields(db);
            }
            when 'Retail' {
                addRetailFields(db);
            }
            when 'Residential Property' {
                addResidentialPropertyFields(db);
            }
        }
       
    }
    
    /**
     * Applies aggregated values to an Opportunity
     */
    public void applyToOpportunity(Opportunity opp) {
        // Common fields - use replace instead of addTo for recalculation scenarios
        opp.Amount = totalAmount;
        opp.Service_Area_Sqm__c = totalServiceAreaSqm;
        opp.Terrace_Area_Sqm__c = totalTerraceAreaSqm;
        opp.Service_Area_SAR__c = totalServiceAreaSAR;
        opp.Terrace_Area_SAR__c = totalTerraceAreaSAR;
        opp.Unit_Size_SQM__c = totalUnitSize;
        opp.Minimum_Acceptable_Rent__c = totalMinimumAcceptableRent;
        
        //switch case for record type
        switch on recordTypeName {
            when 'Offices' {
                applyOfficeFields(opp);
            }
            when 'Retail' {
                applyRetailFields(opp);
            }
            when 'Residential Property' {
                applyResidentialPropertyFields(opp);
            }
        }
       
    }
    
    // ========================================================================
    // PRIVATE HELPER METHODS
    // ========================================================================
    
    private void addOfficeFields(Deal_Building__c db) {
        totalUnitSize += nvl(db.Unit_Area_Sqm_NSA__c);
        totalUnitAreaSqmNSA += nvl(db.Unit_Area_Sqm_NSA__c);
        totalNSA += nvl(db.Total_NSA__c);
        totalPricesServicesAreas += nvl(db.Total_Prices_Services_Areas__c);
        totalPricesTerraceAreas += nvl(db.Total_Prices_Terraces_Areas__c);
        totalLobbyAreaSqm += nvl(db.Lobby_Area_Sqm__c);
        totalPricesLobby += nvl(db.Total_Prices_Lobby__c);
        totalLeasingRate += nvl(db.Leasing_Rate_Sqm_SAR__c);
        totalLeasableAreaSqm += nvl(db.Total_Leasable_Area_Sqm__c);
        totalMinimumAcceptableRent += nvl(db.Total_NSA__c);
        
        if (db.Total_Selling_Price_SAR__c != 0 && db.Total_Leasable_Area_Sqm__c != 0) {
            totalSellingPriceForRate += db.Total_Selling_Price_SAR__c;
        }
    }
    
    private void addRetailFields(Deal_Building__c db) {
        totalUnitSize += nvl(db.Unit_Area_Sqm__c);
        totalUnitAreaSqm += nvl(db.Unit_Area_Sqm__c);
        totalAskingPrice += nvl(db.Asking_Price__c);
        totalAnnualRent += nvl(db.Total_Selling_Price_SAR__c);
        totalMinimumAcceptableRent += nvl(db.Minimum_Annual_Rent__c);
        
        if (String.isNotBlank(db.Unit_No__c)) {
            unitNumbers.add(db.Unit_No__c);
        }
    }

    //add residential property fields
    private void addResidentialPropertyFields(Deal_Building__c db) {
        
        
        totalLandArea += nvl(db.LandArea__c);
        totalLandSellableAmount += nvl(db.LandSellableAmount__c);
        totalVillaArea += nvl(db.VillaArea__c);
        totalVillaSellableAreaSqm += nvl(db.VillaSellableAreaSqm__c);
        totalPreLaunchPrice += nvl(db.PreLaunchPrice__c);
        totalAskingPrice += nvl(db.Asking_Price__c);
        totalSellingPrice += nvl(db.Total_Selling_Price_SAR__c);
        
    }
    
    private void applyOfficeFields(Opportunity opp) {
        opp.Unit_Area_Sqm__c = totalUnitAreaSqmNSA;
        opp.Total_Prices_Unit_Area__c = totalNSA;
        opp.Total_Prices_Service_Area__c = totalPricesServicesAreas;
        opp.Total_Prices_Terrace_Area__c = totalPricesTerraceAreas;
        opp.Lobby_Area_Sqm__c = totalLobbyAreaSqm;
        opp.Total_Prices_Lobby_Areas__c = totalPricesLobby;
        opp.Total_Asking_Rent_SR__c = totalNSA;
        opp.Area_Sqm__c = totalLeasableAreaSqm;
        opp.Total_Annual_Rent_SR_Annum__c = totalAmount;
        
        // Calculate derived fields
        opp.Price_Sqm_SAR_Unit__c = safeDivide(opp.Total_Prices_Unit_Area__c, opp.Unit_Area_Sqm__c);
        opp.Price_Sqm_SAR_Service__c = safeDivide(opp.Total_Prices_Service_Area__c, opp.Service_Area_Sqm__c);
        opp.Price_Sqm_SAR_Terrace__c = safeDivide(opp.Total_Prices_Terrace_Area__c, opp.Terrace_Area_Sqm__c);
        opp.Price_Sqm_SAR_Lobby__c = safeDivide(opp.Total_Prices_Lobby_Areas__c, opp.Lobby_Area_Sqm__c);
        opp.Rate_per_Sqm_SR_Sqm__c = safeDivide(opp.Total_Annual_Rent_SR_Annum__c, opp.Area_Sqm__c);
        opp.Asking_Rate_Sqm__c = safeDivide(opp.Total_Asking_Rent_SR__c, opp.Unit_Size_SQM__c);
        opp.Minimum_Acceptable_Rate_Sqm_SR_Sqm__c = safeDivide(opp.Total_Asking_Rent_SR__c, opp.Unit_Size_SQM__c);
    }
    
    private void applyRetailFields(Opportunity opp) {
        opp.Area_Sqm__c = totalUnitAreaSqm;
        opp.Total_Annual_Rent__c = totalAnnualRent;
        
        if (!unitNumbers.isEmpty()) {
            opp.Unit_Number__c = String.join(unitNumbers, ',');
        }
        
        opp.Rate_per_Sqm_SR_Sqm__c = safeDivide(opp.Total_Annual_Rent__c, opp.Area_Sqm__c);
    }

    private void applyResidentialPropertyFields(Opportunity opp) {
        opp.LandArea__c = totalLandArea;
        opp.LandSellableAmount__c = totalLandSellableAmount;
        opp.BuildUpArea__c = totalVillaArea;
        //opp.VillaSellableAreaSqm__c = totalVillaSellableAreaSqm;
        opp.PreLaunchPrice__c = totalPreLaunchPrice;
        opp.Amount = totalAskingPrice;
        opp.TotalSellingPrice__c = totalAskingPrice;
    }
    
  
    private Decimal addTo(Decimal existing, Decimal toAdd) {
        return nvl(existing) + toAdd;
    }
    
    private Decimal safeDivide(Decimal numerator, Decimal denominator) {
        if (numerator == null || denominator == null || denominator == 0) {
            return 0;
        }
        return numerator / denominator;
    }
    
    private Decimal nvl(Decimal value) {
        return value == null ? 0 : value;
    }
}