force-app/main/default/objects/Building__c/Building__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Building__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available Units</fullName>
                <color>#FF0000</color>
                <default>true</default>
                <label>Available Units</label>
            </value>
            <value>
                <fullName>Offered</fullName>
                <color>#FF9900</color>
                <label>Offered</label>
            </value>
            <value>
                <fullName>Booked</fullName>
                <color>#419249</color>
                <label>Booked</label>
            </value>
            <value>
                <fullName>Booked &amp; Paid</fullName>
                <color>#3366FF</color>
                <label>Booked &amp; Paid</label>
            </value>
            <value>
                <fullName>Signed &amp; Paid</fullName>
                <color>#993399</color>
                <label>Signed &amp; Paid</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal_Building__c/Deal_Building__c.object-meta.xml
<CustomObject>
    <label>Deal Unit</label>
    <nameField>
        <displayFormat>DU# {00000000}</displayFormat>
        <label>Deal Unit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_Building__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipName>Deal_Buildings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Building__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Deal_Buildings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contract_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_End_Date__c</fullName>
    <formula>IF(Term_of_Lease_Years__c &gt; 0, Contract_Start_Date__c + (Term_of_Lease_Years__c *365),
IF(Term_of_Lease_Months__c &gt; 0,ADDMONTHS(Contract_Start_Date__c , Term_of_Lease_Months__c ),
IF(Term_of_Lease_Days__c &gt; 0,Contract_Start_Date__c + Term_of_Lease_Days__c ,
NULL)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contract End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/ContractDateLostClass.cls
public class ContractDateLostClass implements Schedulable {
	public void execute(SchedulableContext ctx) {
        List<Opportunity> opptys = [SELECT Id, Name, OwnerId, CloseDate, Contract_End_Date__c
            FROM Opportunity
            WHERE Contract_End_Date__c < TODAY];
        Map<String, Opportunity> oppMap = new Map<String, Opportunity>();
        Map<String, String> mapDelBuildings = new Map<String, String>();
        for(Opportunity opp :opptys){
        	System.debug('opptys '+opp.Name+' ---- '+opp.Contract_End_Date__c+' ------ '+Date.today());
            oppMap.put(opp.Id, opp);
        }
        
        if(oppMap.keySet().size() > 0){
            for(Deal_Building__c db :[SELECT Id, Deal__c, Building__c FROM Deal_Building__c WHERE Deal__c IN: oppMap.keySet()]){
                mapDelBuildings.put(db.Building__c, db.Deal__c);
                System.debug('db.Id '+db.Id);
            }
            
            List<Building__c> lstBDoupdate = new List<Building__c>();
            
            for(Building__c bd :[SELECT Id, Status__c FROM Building__c WHERE Id IN :mapDelBuildings.keySet()]){
                    bd.Status__c = 'Available Units';
                    lstBDoupdate.add(bd); 	   
            }
            
            update lstBDoupdate;
    	}
        
    }
}