force-app/main/default/objects/Building__c/Building__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Building__c/fields/Asking_Price__c.field-meta.xml
<CustomField>
    <fullName>Asking_Price__c</fullName>
    <label>Asking Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Building__c/fields/Center_Name__c.field-meta.xml
<CustomField>
    <fullName>Center_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Center Name</label>
    <referenceTo>Center__c</referenceTo>
    <relationshipName>Buildings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Building__c/fields/LandSellableAreaSqm__c.field-meta.xml
<CustomField>
    <fullName>LandSellableAreaSqm__c</fullName>
    <label>Land Sellable Area / Sqm</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Building__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available Units</fullName>
                <color>#FF0000</color>
                <default>true</default>
                <label>Available Units</label>
            </value>
            <value>
                <fullName>Offered</fullName>
                <color>#FF9900</color>
                <label>Offered</label>
            </value>
            <value>
                <fullName>Booked</fullName>
                <color>#419249</color>
                <label>Booked</label>
            </value>
            <value>
                <fullName>Booked &amp; Paid</fullName>
                <color>#3366FF</color>
                <label>Booked &amp; Paid</label>
            </value>
            <value>
                <fullName>Signed &amp; Paid</fullName>
                <color>#993399</color>
                <label>Signed &amp; Paid</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Building__c/fields/Total_Selling_Price_SAR__c.field-meta.xml
<CustomField>
    <fullName>Total_Selling_Price_SAR__c</fullName>
    <label>Total Selling Price SAR</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Building__c/fields/VillaSellableAreaSqm__c.field-meta.xml
<CustomField>
    <fullName>VillaSellableAreaSqm__c</fullName>
    <label>Villa Sellable Area / Sqm</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Building__c/recordTypes/Offices.recordType-meta.xml
<RecordType>
    <fullName>Offices</fullName>
    <active>true</active>
    <label>Offices</label>
</RecordType>

force-app/main/default/objects/Center__c/Center__c.object-meta.xml
<CustomObject>
    <label>Center</label>
    <nameField>
        <label>Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_Building__c/Deal_Building__c.object-meta.xml
<CustomObject>
    <label>Deal Unit</label>
    <nameField>
        <displayFormat>DU# {00000000}</displayFormat>
        <label>Deal Unit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_Building__c/fields/Asking_Price__c.field-meta.xml
<CustomField>
    <fullName>Asking_Price__c</fullName>
    <formula>Building__r.Asking_Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Asking Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Deal_Building__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipName>Deal_Buildings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Building__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Deal_Buildings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Building__c/fields/LandSellableAreaSqm__c.field-meta.xml
<CustomField>
    <fullName>LandSellableAreaSqm__c</fullName>
    <formula>Building__r.LandSellableAreaSqm__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Land Sellable Area Sqm</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Deal_Building__c/fields/Total_Selling_Price_SAR__c.field-meta.xml
<CustomField>
    <fullName>Total_Selling_Price_SAR__c</fullName>
    <label>Total Selling Price SAR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Deal_Building__c/fields/VillaSellableAreaSqm__c.field-meta.xml
<CustomField>
    <fullName>VillaSellableAreaSqm__c</fullName>
    <formula>Building__r.VillaSellableAreaSqm__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Villa Sellable Area Sqm</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Deal_Offered_Date__c.field-meta.xml
<CustomField>
    <fullName>Deal_Offered_Date__c</fullName>
    <label>Deal Offered Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/LandPricePerSqm__c.field-meta.xml
<CustomField>
    <fullName>LandPricePerSqm__c</fullName>
    <label>Land Price Per Sqm</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Offer_Valid_till__c.field-meta.xml
<CustomField>
    <fullName>Offer_Valid_till__c</fullName>
    <label>Offer Valid till</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PaymentPlan__c.field-meta.xml
<CustomField>
    <fullName>PaymentPlan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Plan</label>
    <referenceTo>PaymentPlan__c</referenceTo>
    <relationshipLabel>Deals</relationshipLabel>
    <relationshipName>Deals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Rate_per_Sqm_SR_Sqm__c.field-meta.xml
<CustomField>
    <fullName>Rate_per_Sqm_SR_Sqm__c</fullName>
    <label>Rate per Sqm (SR/Sqm)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4) OR (5 AND 6) OR 7 OR (8 AND 9)</booleanFilter>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Offices</value>
        </filterItems>
        <filterItems>
            <field>Center__c.Unit_Record_Type__c</field>
            <operation>contains</operation>
            <value>Offices</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Residential</value>
        </filterItems>
        <filterItems>
            <field>Center__c.Unit_Record_Type__c</field>
            <operation>contains</operation>
            <value>Residential</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Retail</value>
        </filterItems>
        <filterItems>
            <field>Center__c.Unit_Record_Type__c</field>
            <operation>contains</operation>
            <value>Retail</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Special Leasing</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Residential Property</value>
        </filterItems>
        <filterItems>
            <field>Center__c.Unit_Record_Type__c</field>
            <operation>equals</operation>
            <value>Residential</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Center__c</referenceTo>
    <relationshipLabel>Deals</relationshipLabel>
    <relationshipName>Deals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TotalSellingPrice__c.field-meta.xml
<CustomField>
    <fullName>TotalSellingPrice__c</fullName>
    <label>Total Selling Price</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Offices.recordType-meta.xml
<RecordType>
    <fullName>Offices</fullName>
    <active>true</active>
    <businessProcess>Offices</businessProcess>
    <label>Offices</label>
</RecordType>

force-app/main/default/objects/PaymentPlan__c/PaymentPlan__c.object-meta.xml
<CustomObject>
    <label>Payment Plan</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ControllerCreateDeal.cls
public with sharing class ControllerCreateDeal {
 
 
    public static Id getRecordTypeId(String sObjectName, String recordTypeName) {
    if (String.isBlank(sObjectName) || String.isBlank(recordTypeName)) {
        return null;
    }

    Map<String, Schema.SObjectType> globalDescribe = Schema.getGlobalDescribe();

    if (!globalDescribe.containsKey(sObjectName)) {
        return null;
    }

    Schema.DescribeSObjectResult describeResult =
        globalDescribe.get(sObjectName).getDescribe();

    Map<String, Schema.RecordTypeInfo> recordTypeInfos =
        describeResult.getRecordTypeInfosByName();

    if (!recordTypeInfos.containsKey(recordTypeName)) {
        return null;
    }

    return recordTypeInfos.get(recordTypeName).getRecordTypeId();
}

    @AuraEnabled(cacheable=true)
    public static List<PaymentPlan__c> getAllPaymentPlans(String recordTypeId) {
        return [SELECT Id, Name 
                FROM PaymentPlan__c 
                WHERE RecordTypeId = :recordTypeId 
                ORDER BY Name];
    }


    @AuraEnabled(cacheable = true)
    public static Building__c getBulding(String oppId){
            return [SELECT Id, RecordType.Name, Center_Name__c, Center_Name__r.Name FROM Building__c WHERE Id =:oppId limit 1];
    }

    @AuraEnabled(cacheable = false)
    public static void createDeal(String buildId, 
                                        String name, 
                                        String closeDate,
                                        String stage,
                                 		String recordTypeName,
                                 		String siteId,
                                        String tenantsName1){
        
        Id recordTypeId = getRecordTypeId('Opportunity', recordTypeName);
        If(recordTypeId == null){
            throw new AuraHandledException('Record type not found');
        }

        BuildingRepository buildingRepository = new BuildingRepository();
        Map<Id, Building__c> buildings = buildingRepository.getAllFields(new Set<Id>{buildId});
        Building__c bg = buildings.get(buildId);
        bg.Status__c = stage;

        update bg;

        Opportunity opp = new Opportunity();
        opp.Name = name;
        //if(!Test.isRunningTest()){
        	opp.RecordTypeId = recordTypeId;   
       // }
		opp.Site__c = siteId;
        opp.StageName = stage;
        opp.CloseDate = Date.valueOf(closeDate);
        opp.AccountId = tenantsName1;
        opp.LandPricePerSqm__c = bg.LandSellableAreaSqm__c;
        opp.Rate_per_Sqm_SR_Sqm__c = bg.VillaSellableAreaSqm__c;
        opp.TotalSellingPrice__c  =bg.Asking_Price__c;
        opp.Deal_Offered_Date__c = Date.today();
        opp.Offer_Valid_till__c = Date.today().addDays(14);
        insert opp;
        
       
        
        Deal_Building__c db = new Deal_Building__c();
        db.Deal__c = opp.Id;
        db.Building__c = buildId;
        db.Total_Selling_Price_SAR__c = bg.Total_Selling_Price_SAR__c;
       
        insert db;
                                            
    }

//sample to call createDealWithPaymentPlan
//ControllerCreateDeal.createDealWithPaymentPlan('a00000000000000000000000', 'Test', String.valueOf(Date.today()), 'Offered', 'Offices', null, null, 'a00000000000000000000000');
    @AuraEnabled(cacheable = false)
    public static void createDealWithPaymentPlan(String buildId, 
                                        String name, 
                                        String closeDate,
                                        String stage,
                                 		String recordTypeName,
                                 		String siteId,
                                        String tenantsName1,
                                        String paymentPlanId){

        Id recordTypeId = getRecordTypeId('Opportunity', recordTypeName);
        If(recordTypeId == null){
            throw new AuraHandledException('Record type not found');
        }

        BuildingRepository buildingRepository = new BuildingRepository();
        Map<Id, Building__c> buildings = buildingRepository.getAllFields(new Set<Id>{buildId});
        Building__c bg = buildings.get(buildId);
        bg.Status__c = stage;

        update bg;

        Opportunity opp = new Opportunity();
        opp.Name = name;
        //if(!Test.isRunningTest()){
            opp.RecordTypeId = recordTypeId;   
        // }
        opp.Site__c = siteId;
        opp.StageName = stage;
        opp.CloseDate = Date.valueOf(closeDate);
        opp.AccountId = tenantsName1;
        opp.LandPricePerSqm__c = bg.LandSellableAreaSqm__c;
        opp.Rate_per_Sqm_SR_Sqm__c = bg.VillaSellableAreaSqm__c;
        opp.TotalSellingPrice__c  =bg.Asking_Price__c;
        opp.Deal_Offered_Date__c = Date.today();
        opp.Offer_Valid_till__c = Date.today().addDays(14);
        opp.PaymentPlan__c = paymentPlanId;
        insert opp;
        
        
        
        Deal_Building__c db = new Deal_Building__c();
        db.Deal__c = opp.Id;
        db.Building__c = buildId;
        db.RecordTypeId = getRecordTypeId('Deal_Building__c', recordTypeName);
        db.Total_Selling_Price_SAR__c = bg.Total_Selling_Price_SAR__c;
        
        insert db;

        
    }
}