force-app/main/default/objects/Building__c/Building__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Building__c/fields/Asking_Annual_Rent__c.field-meta.xml
<CustomField>
    <fullName>Asking_Annual_Rent__c</fullName>
    <formula>IF( RecordType.Name =&apos;Retail&apos;, Asking_Price__c,0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Asking Annual Rent</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Building__c/fields/Center_Name__c.field-meta.xml
<CustomField>
    <fullName>Center_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Center Name</label>
    <referenceTo>Center__c</referenceTo>
    <relationshipName>Buildings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Building__c/fields/Gross_Leasable_Amount_SAR__c.field-meta.xml
<CustomField>
    <fullName>Gross_Leasable_Amount_SAR__c</fullName>
    <formula>Total_NSA__c+Total_Prices_Services_Areas__c+Total_Prices_Terraces_Areas__c+Total_Prices_Lobby_Areas__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Total (NSA) + Total Prices (Services Areas) + Total Prices (Terraces Areas)</inlineHelpText>
    <label>Gross Leasable Amount SAR</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Building__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available Units</fullName>
                <color>#FF0000</color>
                <default>true</default>
                <label>Available Units</label>
            </value>
            <value>
                <fullName>Offered</fullName>
                <color>#FF9900</color>
                <label>Offered</label>
            </value>
            <value>
                <fullName>Booked</fullName>
                <color>#419249</color>
                <label>Booked</label>
            </value>
            <value>
                <fullName>Booked &amp; Paid</fullName>
                <color>#3366FF</color>
                <label>Booked &amp; Paid</label>
            </value>
            <value>
                <fullName>Signed &amp; Paid</fullName>
                <color>#993399</color>
                <label>Signed &amp; Paid</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Building__c/fields/Total_Selling_Price_SAR__c.field-meta.xml
<CustomField>
    <fullName>Total_Selling_Price_SAR__c</fullName>
    <label>Total Selling Price SAR</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Building__c/recordTypes/Offices.recordType-meta.xml
<RecordType>
    <fullName>Offices</fullName>
    <active>true</active>
    <label>Offices</label>
</RecordType>

force-app/main/default/objects/Building__c/recordTypes/Residential.recordType-meta.xml
<RecordType>
    <fullName>Residential</fullName>
    <active>true</active>
    <label>Residential</label>
</RecordType>

force-app/main/default/objects/Building__c/recordTypes/Retail.recordType-meta.xml
<RecordType>
    <fullName>Retail</fullName>
    <active>true</active>
    <label>Retail</label>
</RecordType>

force-app/main/default/objects/Center__c/Center__c.object-meta.xml
<CustomObject>
    <label>Center</label>
    <nameField>
        <label>Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Center__c/fields/Unit_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Record_Type__c</fullName>
    <label>Unit Record Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Offices</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Standard Retail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal_Building__c/Deal_Building__c.object-meta.xml
<CustomObject>
    <label>Deal Unit</label>
    <nameField>
        <displayFormat>DU# {00000000}</displayFormat>
        <label>Deal Unit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_Building__c/fields/Asking_Annual_Rent__c.field-meta.xml
<CustomField>
    <fullName>Asking_Annual_Rent__c</fullName>
    <formula>IF(Building__r.Asking_Annual_Rent__c &gt; 0,Building__r.Asking_Annual_Rent__c,
Deal__r.Total_Asking_Rent_SR__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Asking Annual Rent</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Deal_Building__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipName>Deal_Buildings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Building__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Deal_Buildings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Building__c/fields/Gross_Leasable_Amount_SAR__c.field-meta.xml
<CustomField>
    <fullName>Gross_Leasable_Amount_SAR__c</fullName>
    <formula>Total_NSA__c+Total_Prices_Services_Areas__c+Total_Prices_Terraces_Areas__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Total (NSA) + Total Prices (Services Areas) + Total Prices (Terraces Areas)</inlineHelpText>
    <label>Gross Leasable Amount SAR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Deal_Building__c/fields/Total_Selling_Price_SAR__c.field-meta.xml
<CustomField>
    <fullName>Total_Selling_Price_SAR__c</fullName>
    <label>Total Selling Price SAR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4) OR (5 AND 6) OR 7 OR (8 AND 9)</booleanFilter>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Offices</value>
        </filterItems>
        <filterItems>
            <field>Center__c.Unit_Record_Type__c</field>
            <operation>contains</operation>
            <value>Offices</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Residential</value>
        </filterItems>
        <filterItems>
            <field>Center__c.Unit_Record_Type__c</field>
            <operation>contains</operation>
            <value>Residential</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Retail</value>
        </filterItems>
        <filterItems>
            <field>Center__c.Unit_Record_Type__c</field>
            <operation>contains</operation>
            <value>Retail</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Special Leasing</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Residential Property</value>
        </filterItems>
        <filterItems>
            <field>Center__c.Unit_Record_Type__c</field>
            <operation>equals</operation>
            <value>Residential</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Center__c</referenceTo>
    <relationshipLabel>Deals</relationshipLabel>
    <relationshipName>Deals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Offices.recordType-meta.xml
<RecordType>
    <fullName>Offices</fullName>
    <active>true</active>
    <businessProcess>Offices</businessProcess>
    <label>Offices</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Residential.recordType-meta.xml
<RecordType>
    <fullName>Residential</fullName>
    <active>true</active>
    <businessProcess>Offices</businessProcess>
    <label>Residential</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Retail.recordType-meta.xml
<RecordType>
    <fullName>Retail</fullName>
    <active>true</active>
    <businessProcess>Retail</businessProcess>
    <label>Retail</label>
</RecordType>

force-app/main/default/classes/DealBildingTriggerHandlerTest.cls
@IsTest
private class DealBildingTriggerHandlerTest {

    // ─── Test Data Setup ─────────────────────────────────────────────────────

    @TestSetup
    static void makeData() {
        insert new Account(Name = 'Test Account');

        // Centers must satisfy Site__c lookup filter per Opportunity RT
        Center__c officesCenter = new Center__c(
            Name                = 'Residential Center',
            Unit_Record_Type__c = 'Residential'
        );
        Center__c retailCenter = new Center__c(
            Name                = 'Retail Center',
            Unit_Record_Type__c = 'Retail'
        );
        insert new List<Center__c>{ officesCenter, retailCenter };

        // Buildings (no RT required by trigger logic)
        Building__c officesBldg = new Building__c(
            Name                       = 'Residential Building',            
            Total_Selling_Price_SAR__c   = 100000,
            Center_Name__c               = officesCenter.Id
        );
        Building__c retailBldg = new Building__c(
            Name                       = 'Retail Building',
            Total_Selling_Price_SAR__c = 80000,
            Center_Name__c             = retailCenter.Id
        );
        insert new List<Building__c>{ officesBldg, retailBldg };

        Id officesRtId = Schema.SObjectType.Opportunity
                             .getRecordTypeInfosByName().get('Residential').getRecordTypeId();
        Id retailRtId  = Schema.SObjectType.Opportunity
                             .getRecordTypeInfosByName().get('Retail').getRecordTypeId();

        Account acc = [SELECT Id FROM Account LIMIT 1];

        Opportunity officesOpp = new Opportunity(
            Name         = 'Test Residential Deal',
            StageName    = 'Offered',
            CloseDate    = Date.today().addDays(30),
            AccountId    = acc.Id,
            RecordTypeId = officesRtId,
            Site__c      = officesCenter.Id
        );
        Opportunity retailOpp = new Opportunity(
            Name         = 'Test Retail Deal',
            StageName    = 'Offered',
            CloseDate    = Date.today().addDays(30),
            AccountId    = acc.Id,
            RecordTypeId = retailRtId,
            Site__c      = retailCenter.Id
        );
        insert new List<Opportunity>{ officesOpp, retailOpp };
    }

    // ─── onBeforeInsert + onAfterInsert: Offices RT ──────────────────────────
    // Covers DealBuildingBeforeInsert.beforeInsert (Offices branch sets Total_Selling_Price_SAR__c
    // from Gross_Leasable_Amount_SAR__c) and DealBuildingBeforeInsert.afterInsert aggregation.

    @IsTest
    static void testInsert_ResidentialRT() {
        Opportunity opp  = [SELECT Id FROM Opportunity WHERE Name = 'Test Residential Deal' LIMIT 1];
        Building__c bldg = [SELECT Id, Gross_Leasable_Amount_SAR__c FROM Building__c WHERE Name = 'Residential Building' LIMIT 1];

        Test.startTest();
        Deal_Building__c db = new Deal_Building__c(
            Deal__c     = opp.Id,
            Building__c = bldg.Id
        );
        insert db;
        Test.stopTest();

        Deal_Building__c result = [SELECT Id, Total_Selling_Price_SAR__c FROM Deal_Building__c WHERE Id = :db.Id];
        System.assertNotEquals(null, result.Id, 'Deal_Building__c should have been inserted');
        System.assertEquals(
            bldg.Gross_Leasable_Amount_SAR__c,
            result.Total_Selling_Price_SAR__c,
            'beforeInsert should set Total_Selling_Price_SAR__c from Gross_Leasable_Amount_SAR__c for Offices RT'
        );
    }

    // ─── onBeforeInsert + onAfterInsert: Retail RT ───────────────────────────
    // Covers the Retail branch in DealBuildingBeforeInsert.beforeInsert (sets
    // Total_Selling_Price_SAR__c from Asking_Annual_Rent__c).

    @IsTest
    static void testInsert_RetailRT() {
        Opportunity opp  = [SELECT Id FROM Opportunity WHERE Name = 'Test Retail Deal' LIMIT 1];
        Building__c bldg = [SELECT Id, Asking_Annual_Rent__c FROM Building__c WHERE Name = 'Retail Building' LIMIT 1];

        Test.startTest();
        Deal_Building__c db = new Deal_Building__c(
            Deal__c     = opp.Id,
            Building__c = bldg.Id
        );
        insert db;
        Test.stopTest();

        Deal_Building__c result = [SELECT Id, Total_Selling_Price_SAR__c FROM Deal_Building__c WHERE Id = :db.Id];
        System.assertNotEquals(null, result.Id, 'Deal_Building__c should have been inserted for Retail opportunity');
        System.assertEquals(
            bldg.Asking_Annual_Rent__c,
            result.Total_Selling_Price_SAR__c,
            'beforeInsert should set Total_Selling_Price_SAR__c from Asking_Annual_Rent__c for Retail RT'
        );
    }

    // ─── onAfterUpdate ───────────────────────────────────────────────────────
    // Covers DealBuildingUpdate.afterUpdate — changes to Total_Selling_Price_SAR__c
    // trigger propagation to the parent Opportunity (Amount field).

    @IsTest
    static void testAfterUpdate() {
        Opportunity opp  = [SELECT Id FROM Opportunity WHERE Name = 'Test Residential Deal' LIMIT 1];
        Building__c bldg = [SELECT Id FROM Building__c WHERE Name = 'Residential Building' LIMIT 1];

        Deal_Building__c db = new Deal_Building__c(
            Deal__c     = opp.Id,
            Building__c = bldg.Id
        );
        insert db;

        Test.startTest();
        db.Total_Selling_Price_SAR__c = 200000;
        update db;
        Test.stopTest();

        Deal_Building__c updated = [SELECT Id, Total_Selling_Price_SAR__c FROM Deal_Building__c WHERE Id = :db.Id];
        System.assertEquals(200000, updated.Total_Selling_Price_SAR__c,
            'Total_Selling_Price_SAR__c should reflect the updated value');

        Opportunity oAfter = [SELECT Id, Amount FROM Opportunity WHERE Id = :opp.Id];
        System.assertNotEquals(null, oAfter.Id, 'Opportunity should still exist after Deal_Building update');
    }

    // ─── onAfterDelete ───────────────────────────────────────────────────────
    // Covers DealBuildingDelete.afterDelete — deleting a Deal_Building resets
    // the Building Status__c to 'Available Units' and adjusts the parent Opportunity.

    @IsTest
    static void testAfterDelete() {
        Opportunity opp  = [SELECT Id FROM Opportunity WHERE Name = 'Test Residential Deal' LIMIT 1];
        Building__c bldg = [SELECT Id FROM Building__c WHERE Name = 'Residential Building' LIMIT 1];

        Deal_Building__c db = new Deal_Building__c(
            Deal__c     = opp.Id,
            Building__c = bldg.Id
        );
        insert db;

        Test.startTest();
        delete db;
        Test.stopTest();

        Integer count = [SELECT COUNT() FROM Deal_Building__c WHERE Deal__c = :opp.Id];
        System.assertEquals(0, count, 'Deal_Building__c should have been deleted');

        Building__c bldgAfter = [SELECT Id, Status__c FROM Building__c WHERE Id = :bldg.Id];
        System.assertEquals('Available Units', bldgAfter.Status__c,
            'Building Status__c should be reset to Available Units after Deal_Building deletion');
    }
}