force-app/main/default/objects/Building__c/Building__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Building__c/fields/Total_Selling_Price_SAR__c.field-meta.xml
<CustomField>
    <fullName>Total_Selling_Price_SAR__c</fullName>
    <label>Total Selling Price SAR</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Building__c/recordTypes/Retail.recordType-meta.xml
<RecordType>
    <fullName>Retail</fullName>
    <active>true</active>
    <label>Retail</label>
</RecordType>

force-app/main/default/objects/Deal_Building__c/Deal_Building__c.object-meta.xml
<CustomObject>
    <label>Deal Unit</label>
    <nameField>
        <displayFormat>DU# {00000000}</displayFormat>
        <label>Deal Unit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_Building__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipName>Deal_Buildings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Building__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Deal_Buildings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Building__c/fields/Total_Selling_Price_SAR__c.field-meta.xml
<CustomField>
    <fullName>Total_Selling_Price_SAR__c</fullName>
    <label>Total Selling Price SAR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contract_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Start_Date__c</fullName>
    <label>Contract Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Term_of_Lease_Years__c.field-meta.xml
<CustomField>
    <fullName>Term_of_Lease_Years__c</fullName>
    <label>Term of Lease (Years)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Total_Annual_Rent_SR_Annum__c.field-meta.xml
<CustomField>
    <fullName>Total_Annual_Rent_SR_Annum__c</fullName>
    <label>Total Annual Rent SR/Annum</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Retail.recordType-meta.xml
<RecordType>
    <fullName>Retail</fullName>
    <active>true</active>
    <businessProcess>Retail</businessProcess>
    <label>Retail</label>
</RecordType>

force-app/main/default/classes/UpdateBuildingStatusTEST.cls
@istest
public class UpdateBuildingStatusTEST {
    testmethod static void testscheduleUpdateBuildings(){
        
    	Opportunity opp = new Opportunity();
        opp.End_Date__c = Date.today();
        opp.Name = 'Test';
        opp.StageName = 'Offered';
        opp.CloseDate = Date.today();
        opp.Amount = 1000;
        opp.Contract_Start_Date__c  = date.today().addYears(-2);
        opp.Term_of_Lease_Years__c  = 1;
        opp.Total_Annual_Rent_SR_Annum__c = 2000;
        insert opp;
        
        Building__c build = new Building__c();
        build.Name = 'Test';
        
        insert build;
        
        Deal_Building__c dealB = new Deal_Building__c();
        dealB.Deal__c = opp.Id;
        dealB.Building__c = build.Id;
        
        insert dealB;
        dealB.Total_Selling_Price_SAR__c = 1000;
        update dealB;
        
        DealJunkTableController.getRelatedDealBuilding(opp.Id);
        DealJunkTableController.createJunctionObject(opp.Id, build.Id);
        ControllerCreateDeal.getBulding(build.Id);
        ControllerCreateDeal.createDeal(build.Id, 'Retail Name', String.valueOf(Date.today()), 'Offered', 'Retail', null, null);
            
        UpdateBuildingStatus cvSLS = new UpdateBuildingStatus();
        String sch = '0 0 23 * * ?';
        Id jobId = System.schedule('UpdateBuildingStatus', sch, cvSLS);
        delete dealB;
        
        //ContractDateLostClass cvSLS1 = new ContractDateLostClass();
        //String sch1 = '0 0 23 * * ?';
        //Id jobId1 = System.schedule('ContractDateLostClass', sch1, cvSLS1);
        
        opp.StageName = 'Closed Lost';
        update opp;
    }
}