force-app/main/default/objects/Building__c/Building__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Building__c/fields/Asking_Price__c.field-meta.xml
<CustomField>
    <fullName>Asking_Price__c</fullName>
    <label>Asking Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Building__c/fields/Center_Name__c.field-meta.xml
<CustomField>
    <fullName>Center_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Center Name</label>
    <referenceTo>Center__c</referenceTo>
    <relationshipName>Buildings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Building__c/fields/LandSellableAreaSqm__c.field-meta.xml
<CustomField>
    <fullName>LandSellableAreaSqm__c</fullName>
    <label>Land Sellable Area / Sqm</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Building__c/fields/Total_Selling_Price_SAR__c.field-meta.xml
<CustomField>
    <fullName>Total_Selling_Price_SAR__c</fullName>
    <label>Total Selling Price SAR</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Building__c/fields/VillaSellableAreaSqm__c.field-meta.xml
<CustomField>
    <fullName>VillaSellableAreaSqm__c</fullName>
    <label>Villa Sellable Area / Sqm</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Building__c/recordTypes/Offices.recordType-meta.xml
<RecordType>
    <fullName>Offices</fullName>
    <active>true</active>
    <label>Offices</label>
</RecordType>

force-app/main/default/objects/Building__c/recordTypes/Residential.recordType-meta.xml
<RecordType>
    <fullName>Residential</fullName>
    <active>true</active>
    <label>Residential</label>
</RecordType>

force-app/main/default/objects/Center__c/Center__c.object-meta.xml
<CustomObject>
    <label>Center</label>
    <nameField>
        <label>Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Center__c/fields/Unit_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Record_Type__c</fullName>
    <label>Unit Record Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Offices</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Standard Retail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal_Building__c/Deal_Building__c.object-meta.xml
<CustomObject>
    <label>Deal Unit</label>
    <nameField>
        <displayFormat>DU# {00000000}</displayFormat>
        <label>Deal Unit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_Building__c/fields/Asking_Price__c.field-meta.xml
<CustomField>
    <fullName>Asking_Price__c</fullName>
    <formula>Building__r.Asking_Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Asking Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Deal_Building__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipName>Deal_Buildings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Building__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Deal_Buildings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Building__c/fields/LandSellableAreaSqm__c.field-meta.xml
<CustomField>
    <fullName>LandSellableAreaSqm__c</fullName>
    <formula>Building__r.LandSellableAreaSqm__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Land Sellable Area Sqm</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Deal_Building__c/fields/Total_Selling_Price_SAR__c.field-meta.xml
<CustomField>
    <fullName>Total_Selling_Price_SAR__c</fullName>
    <label>Total Selling Price SAR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Deal_Building__c/fields/VillaSellableAreaSqm__c.field-meta.xml
<CustomField>
    <fullName>VillaSellableAreaSqm__c</fullName>
    <formula>Building__r.VillaSellableAreaSqm__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Villa Sellable Area Sqm</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PaymentPlan__c.field-meta.xml
<CustomField>
    <fullName>PaymentPlan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Plan</label>
    <referenceTo>PaymentPlan__c</referenceTo>
    <relationshipLabel>Deals</relationshipLabel>
    <relationshipName>Deals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4) OR (5 AND 6) OR 7 OR (8 AND 9)</booleanFilter>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Offices</value>
        </filterItems>
        <filterItems>
            <field>Center__c.Unit_Record_Type__c</field>
            <operation>contains</operation>
            <value>Offices</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Residential</value>
        </filterItems>
        <filterItems>
            <field>Center__c.Unit_Record_Type__c</field>
            <operation>contains</operation>
            <value>Residential</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Retail</value>
        </filterItems>
        <filterItems>
            <field>Center__c.Unit_Record_Type__c</field>
            <operation>contains</operation>
            <value>Retail</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Special Leasing</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Residential Property</value>
        </filterItems>
        <filterItems>
            <field>Center__c.Unit_Record_Type__c</field>
            <operation>equals</operation>
            <value>Residential</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Center__c</referenceTo>
    <relationshipLabel>Deals</relationshipLabel>
    <relationshipName>Deals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Offices.recordType-meta.xml
<RecordType>
    <fullName>Offices</fullName>
    <active>true</active>
    <businessProcess>Offices</businessProcess>
    <label>Offices</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Residential.recordType-meta.xml
<RecordType>
    <fullName>Residential</fullName>
    <active>true</active>
    <businessProcess>Offices</businessProcess>
    <label>Residential</label>
</RecordType>

force-app/main/default/objects/PaymentPlan__c/PaymentPlan__c.object-meta.xml
<CustomObject>
    <label>Payment Plan</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentPlan__c/fields/Center__c.field-meta.xml
<CustomField>
    <fullName>Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Center</label>
    <referenceTo>Center__c</referenceTo>
    <relationshipLabel>Payment Plans</relationshipLabel>
    <relationshipName>PaymentPlans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ControllerCreateDealTEST.cls
@IsTest
private class ControllerCreateDealTEST {

    // ─── Test Data Setup ─────────────────────────────────────────────────────

    @TestSetup
    static void makeData() {
        insert new Account(Name = 'Test Account');

        
        // Site__c lookup filter (1 AND 2): Opp RT = Offices AND Unit_Record_Type__c contains 'Offices'
        insert new Center__c(
            Name                = 'Residential Center',
            Unit_Record_Type__c = 'Residential'
        );

        // Site__c lookup filter (8 AND 9): Opp RT = Residential Property AND Unit_Record_Type__c = 'Residential'
        insert new Center__c(
            Name                = 'Residential Center',
            Unit_Record_Type__c = 'Residential',
            RecordTypeId        = Schema.SObjectType.Center__c
                                      .getRecordTypeInfosByName()
                                      .get('Residential Property')
                                      .getRecordTypeId()
        );

        insert new Building__c(
            Name                       = 'Test Building',
            LandSellableAreaSqm__c     = 1000,
            VillaSellableAreaSqm__c    = 2000,
            Asking_Price__c            = 500000,
            Total_Selling_Price_SAR__c = 500000,
            Center_Name__c             = [SELECT Id FROM Center__c WHERE Name = 'Residential Center' LIMIT 1].Id,
            RecordTypeId               = Schema.SObjectType.Building__c
                                             .getRecordTypeInfosByName()
                                             .get('Residential')
                                             .getRecordTypeId()
        );

        Id ppRtId = Schema.SObjectType.PaymentPlan__c
                        .getRecordTypeInfosByName()
                        .get('Residential Property')
                        .getRecordTypeId();

        insert new PaymentPlan__c(
            Name         = 'Test Plan',
            RecordTypeId = ppRtId
        );
    }

    // ─── getRecordTypeId ─────────────────────────────────────────────────────
    // Covers: blank sObjectName, blank recordTypeName, unknown RT name, valid case

    @IsTest
    static void testGetRecordTypeId() {
        System.assertEquals(null, ControllerCreateDeal.getRecordTypeId(null, 'Residential'),
            'Null sObjectName should return null');

        System.assertEquals(null, ControllerCreateDeal.getRecordTypeId('Opportunity', null),
            'Null recordTypeName should return null');

        System.assertEquals(null, ControllerCreateDeal.getRecordTypeId('Opportunity', 'NonExistentRT_XYZ'),
            'Unknown record type name should return null');

        Id rtId = ControllerCreateDeal.getRecordTypeId('Opportunity', 'Residential');
        System.assertNotEquals(null, rtId, 'Valid record type name should return an Id');
    }

    // ─── getAllPaymentPlans + getBulding ──────────────────────────────────────

    @IsTest
    static void testGetAllPaymentPlansAndGetBuilding() {
        PaymentPlan__c plan = [SELECT Id, RecordTypeId FROM PaymentPlan__c LIMIT 1];
        Building__c b       = [SELECT Id FROM Building__c LIMIT 1];

        Test.startTest();
        List<PaymentPlan__c> plans = ControllerCreateDeal.getAllPaymentPlans(plan.RecordTypeId);
        Building__c result         = ControllerCreateDeal.getBulding(b.Id);
        Test.stopTest();

        System.assert(plans.size() >= 1, 'Should return at least the test PaymentPlan');
        System.assertEquals(b.Id, result.Id, 'getBulding should return the correct Building record');
    }

    // ─── createDeal ──────────────────────────────────────────────────────────

    @IsTest
    static void testCreateDeal_success() {
        Building__c b = [SELECT Id FROM Building__c LIMIT 1];
        Account a     = [SELECT Id FROM Account LIMIT 1];
        Center__c c   = [SELECT Id FROM Center__c WHERE Name = 'Residential Center' LIMIT 1];

        Test.startTest();
        ControllerCreateDeal.createDeal(
            b.Id, 'Test Deal', String.valueOf(Date.today()),
            'Offered', 'Residential', c.Id, a.Id
        );
        Test.stopTest();

        Opportunity opp = [SELECT Id, StageName FROM Opportunity WHERE Name = 'Test Deal' LIMIT 1];
        System.assertNotEquals(null, opp.Id, 'Opportunity should have been created');
        System.assertEquals('Offered', opp.StageName, 'StageName should match the stage argument');

        Integer dbCount = [SELECT COUNT() FROM Deal_Building__c WHERE Deal__c = :opp.Id];
        System.assertEquals(1, dbCount, 'Exactly one Deal_Building__c should have been created');
    }

    // ─── Exception branches: invalid record type in both create methods ───────

    @IsTest
    static void testCreateDeal_invalidRecordType_throwsException() {
        Building__c b = [SELECT Id FROM Building__c LIMIT 1];

        try {
            ControllerCreateDeal.createDeal(
                b.Id, 'X', String.valueOf(Date.today()), 'Offered', 'NonExistentRT_XYZ', null, null
            );
            System.assert(false, 'createDeal with invalid RT should throw AuraHandledException');
        } catch (AuraHandledException e) {
            System.assert(true, 'AuraHandledException correctly thrown by createDeal');
        }

        try {
            ControllerCreateDeal.createDealWithPaymentPlan(
                b.Id, 'X', String.valueOf(Date.today()), 'Offered', 'NonExistentRT_XYZ', null, null, null
            );
            System.assert(false, 'createDealWithPaymentPlan with invalid RT should throw AuraHandledException');
        } catch (AuraHandledException e) {
            System.assert(true, 'AuraHandledException correctly thrown by createDealWithPaymentPlan');
        }
    }

    // ─── createDealWithPaymentPlan ────────────────────────────────────────────

    @IsTest
    static void testCreateDealWithPaymentPlan_success() {
        Building__c    b    = [SELECT Id FROM Building__c LIMIT 1];
        Account        a    = [SELECT Id FROM Account LIMIT 1];
        Center__c      c    = [SELECT Id FROM Center__c WHERE Name = 'Residential Center' LIMIT 1];
        PaymentPlan__c plan = [SELECT Id FROM PaymentPlan__c LIMIT 1];

        Test.startTest();
        ControllerCreateDeal.createDealWithPaymentPlan(
            b.Id, 'Test Deal PP', String.valueOf(Date.today()),
            'Offered', 'Residential Property', c.Id, a.Id, plan.Id
        );
        Test.stopTest();

        Opportunity opp = [SELECT Id, PaymentPlan__c FROM Opportunity WHERE Name = 'Test Deal PP' LIMIT 1];
        System.assertNotEquals(null, opp.Id, 'Opportunity should have been created');
        System.assertEquals(plan.Id, opp.PaymentPlan__c, 'PaymentPlan__c should be linked to the Opportunity');

        Integer dbCount = [SELECT COUNT() FROM Deal_Building__c WHERE Deal__c = :opp.Id];
        System.assertEquals(1, dbCount, 'Exactly one Deal_Building__c should have been created');
    }
}