force-app/main/default/objects/Building__c/Building__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Building__c/fields/Asking_Annual_Rent__c.field-meta.xml
<CustomField>
    <fullName>Asking_Annual_Rent__c</fullName>
    <formula>IF( RecordType.Name =&apos;Retail&apos;, Asking_Price__c,0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Asking Annual Rent</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Building__c/fields/Client_Asking_Price_SAR__c.field-meta.xml
<CustomField>
    <fullName>Client_Asking_Price_SAR__c</fullName>
    <formula>Unit_Area_Sqm__c  * Ask_Weighted_Rate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Client Asking Price SAR</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Building__c/fields/Gross_Leasable_Amount_SAR__c.field-meta.xml
<CustomField>
    <fullName>Gross_Leasable_Amount_SAR__c</fullName>
    <formula>Total_NSA__c+Total_Prices_Services_Areas__c+Total_Prices_Terraces_Areas__c+Total_Prices_Lobby_Areas__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Total (NSA) + Total Prices (Services Areas) + Total Prices (Terraces Areas)</inlineHelpText>
    <label>Gross Leasable Amount SAR</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Building__c/fields/Total_Selling_Price_SAR__c.field-meta.xml
<CustomField>
    <fullName>Total_Selling_Price_SAR__c</fullName>
    <label>Total Selling Price SAR</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/BuildingRepository.cls
public class BuildingRepository {
    
    public Map<Id, Building__c> getBuildingsWithPricing(Set<Id> buildingIds) {
        return new Map<Id, Building__c>([
            SELECT Id,
                   Gross_Leasable_Amount_SAR__c,
                   Total_Selling_Price_SAR__c,
                   Client_Asking_Price_SAR__c,
                   Asking_Annual_Rent__c
            FROM Building__c 
            WHERE Id IN :buildingIds
        ]);
    }

    public Map<Id, Building__c> getAllFields(Set<Id> buildingIds) {
        String query = 'SELECT ';
        for(Schema.SObjectField field : Schema.getGlobalDescribe().get('Building__c').getDescribe().fields.getMap().values()) {
            query += field.getDescribe().getName() + ',';
        }
        //remove the last comma
        query = query.removeEnd(',');
        query += ' FROM Building__c WHERE Id IN :buildingIds';
        return new Map<Id, Building__c>((List<Building__c>)Database.query(query));
    }
}