force-app/main/default/objects/Building__c/Building__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Building__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available Units</fullName>
                <color>#FF0000</color>
                <default>true</default>
                <label>Available Units</label>
            </value>
            <value>
                <fullName>Offered</fullName>
                <color>#FF9900</color>
                <label>Offered</label>
            </value>
            <value>
                <fullName>Booked</fullName>
                <color>#419249</color>
                <label>Booked</label>
            </value>
            <value>
                <fullName>Booked &amp; Paid</fullName>
                <color>#3366FF</color>
                <label>Booked &amp; Paid</label>
            </value>
            <value>
                <fullName>Signed &amp; Paid</fullName>
                <color>#993399</color>
                <label>Signed &amp; Paid</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal_Building__c/Deal_Building__c.object-meta.xml
<CustomObject>
    <label>Deal Unit</label>
    <nameField>
        <displayFormat>DU# {00000000}</displayFormat>
        <label>Deal Unit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_Building__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipName>Deal_Buildings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Building__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Deal_Buildings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/UpdateBuildingStatus.cls
global class UpdateBuildingStatus Implements Schedulable{
    global void execute(SchedulableContext sc){
        setToStatusBuilding();
    }
    
    public void setToStatusBuilding(){
        List<Opportunity> oppLst = [SELECT Id FROM Opportunity WHERE End_Date__c =: Date.today()];
        Set<Id> lstOppId = new Set<Id>();
        for(Opportunity opp :oppLst){
            System.debug(opp);
            lstOppId.add(opp.Id);
        }
        
        List<Deal_Building__c> dbList = [SELECT Id, Building__c FROM Deal_Building__c WHERE Deal__c IN:lstOppId];
        Set<Id> buildingsId = new Set<Id>();
        for(Deal_Building__c dbItem : dbList){
            buildingsId.add(dbItem.Building__c);
        }
        
        List<Building__c> lstBuildings = [SELECT Id, Status__c FROM Building__c WHERE Id IN:buildingsId];
        List<Building__c> lstBuildingsForUpdate = New List<Building__c>();
        for(Building__c bItem : lstBuildings){
            if(bItem.Status__c != 'Available Units'){
            	bItem.Status__c = 'Available Units';
                lstBuildingsForUpdate.add(bItem);
            }
             
        }
        update lstBuildingsForUpdate;
    }
}