force-app/main/default/objects/Building__c/Building__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Building__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available Units</fullName>
                <color>#FF0000</color>
                <default>true</default>
                <label>Available Units</label>
            </value>
            <value>
                <fullName>Offered</fullName>
                <color>#FF9900</color>
                <label>Offered</label>
            </value>
            <value>
                <fullName>Booked</fullName>
                <color>#419249</color>
                <label>Booked</label>
            </value>
            <value>
                <fullName>Booked &amp; Paid</fullName>
                <color>#3366FF</color>
                <label>Booked &amp; Paid</label>
            </value>
            <value>
                <fullName>Signed &amp; Paid</fullName>
                <color>#993399</color>
                <label>Signed &amp; Paid</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal_Building__c/Deal_Building__c.object-meta.xml
<CustomObject>
    <label>Deal Unit</label>
    <nameField>
        <displayFormat>DU# {00000000}</displayFormat>
        <label>Deal Unit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal_Building__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipName>Deal_Buildings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deal_Building__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Deal_Buildings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4) OR (5 AND 6) OR 7 OR (8 AND 9)</booleanFilter>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Offices</value>
        </filterItems>
        <filterItems>
            <field>Center__c.Unit_Record_Type__c</field>
            <operation>contains</operation>
            <value>Offices</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Residential</value>
        </filterItems>
        <filterItems>
            <field>Center__c.Unit_Record_Type__c</field>
            <operation>contains</operation>
            <value>Residential</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Retail</value>
        </filterItems>
        <filterItems>
            <field>Center__c.Unit_Record_Type__c</field>
            <operation>contains</operation>
            <value>Retail</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Special Leasing</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Residential Property</value>
        </filterItems>
        <filterItems>
            <field>Center__c.Unit_Record_Type__c</field>
            <operation>equals</operation>
            <value>Residential</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Center__c</referenceTo>
    <relationshipLabel>Deals</relationshipLabel>
    <relationshipName>Deals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DealJunkTableControllerTest.cls
@IsTest
private class DealJunkTableControllerTest {

    private static Opportunity createOpportunity(Id siteId) {
        Opportunity opp = new Opportunity(
            Name = 'Deal Junk Opp',
            StageName = 'Offered',
            CloseDate = Date.today().addDays(10),
            Site__c = siteId
        );
        insert opp;
        return opp;
    }

    private static Building__c createBuilding(String name) {
        Building__c building = new Building__c(
            Name = name,
            Status__c = 'Available Units'
        );
        insert building;
        return building;
    }

    @IsTest
    static void getRelatedDealBuilding_shouldReturnRecords() {
        Opportunity opp = createOpportunity(null);
        Building__c building = createBuilding('Deal Junk Building 1');

        insert new Deal_Building__c(
            Deal__c = opp.Id,
            Building__c = building.Id
        );

        Test.startTest();
        List<Deal_Building__c> result = DealJunkTableController.getRelatedDealBuilding(opp.Id);
        Test.stopTest();

        System.assertNotEquals(null, result);
        System.assertEquals(1, result.size());
    }

    @IsTest
    static void createJunctionObject_shouldCreateJunctionAndUpdateStatus() {
        Opportunity opp = createOpportunity(null);
        Building__c building = createBuilding('Deal Junk Building 2');

        Test.startTest();
        DealJunkTableController.createJunctionObject(opp.Id, building.Id);
        Test.stopTest();

        Integer countJunction = [
            SELECT COUNT()
            FROM Deal_Building__c
            WHERE Deal__c = :opp.Id
            AND Building__c = :building.Id
        ];
        System.assertEquals(1, countJunction, 'Should create one Deal_Building__c');

        Building__c updatedBuilding = [
            SELECT Status__c
            FROM Building__c
            WHERE Id = :building.Id
        ];
        System.assertEquals('Offered', updatedBuilding.Status__c);
    }

    @IsTest
    static void searchMethods_shouldReturnWithoutExceptions() {
        Opportunity opp = createOpportunity(null);
        createBuilding('Deal Junk Building 3');

        Test.startTest();
        List<Building__c> residentialResult = DealJunkTableController.getAllBuildingsResidentialProperty(
            '{"fieldAndValue":{}}'
        );
        List<Building__c> buildingsResult = DealJunkTableController.getAllBuildings(
            opp.Id,
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            ''
        );
        Test.stopTest();

        System.assertNotEquals(null, residentialResult);
        System.assertNotEquals(null, buildingsResult);
    }
}